Adding basic openshift-applier tutorial
redhat-cop/katacoda-scenarios pull request #1
Opened 2018-08-27 20:25 UTC by logandonley

Adding a starter openshift-applier katacoda scenario. This can be seen live at https://www.katacoda.com/logandonley/scenarios/openshift-applier.

2018-08-27 22:34 UTC, oybed submitted a review, later dismissed
Looks good for starters - please see inline for some minor comments.

2018-08-27 22:34 UTC, oybed commented on openshift-applier/step1.md
> +    version: v3.9.0
Can you please update to not use the `v3.9.x` release. Either use `v1.0.2`, or `v2.0.0` (preferred).

2018-08-27 22:34 UTC, oybed commented on openshift-applier/step2.md
> +      template_action: create
If you update `openshift-applier` requirement above to use `v2.0.0`, please remember to make this just `action` (rather than `template_action`).

2018-08-27 22:34 UTC, oybed commented
@etsauer @pcarney8 would you have some cycles to help review as well?

2018-08-27 23:04 UTC, etsauer requested changes
A few recommendations.

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/intro.md
> +This tutorial will get you up and running with the OpenShift-Applier.
I think we need at least an introduction statement. Maybe:
```
OpenShift Applier is a framework that helps you automate the lifecycle of OpenShift and Kubernetes resources using [Infrastructure as Code](https://en.wikipedia.org/wiki/Infrastructure_as_Code). This tutorial will get you up and running with OpenShift Applier.

To understand some of the base knowledge and background behind applier, we recommend the following resources:

- http://v1.uncontained.io/playbooks/fundamentals/template_development_guide.html
```

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step1.md
> +For this tutorial we are going to create everything from scratch. In the future, in the future you can use some of the following resources as starting points:
`s/create everything from scratch/create a new _infrastructure as code_ project from scratch/`.
`s/, in the future/,/`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step1.md
> +To begin, let's create a new directory and go into it.
`s/go/cd`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step1.md
> +To complete the generic project structure, we want to create the rest of these:
replace who line with: `A generic directory structure for an Applier project looks like this:`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step1.md
> +
Add line: `Let's go ahead and create our project scaffolding`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step2.md
> +To checkout what the template looks like, run the following:
`s/checkout/check out/`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step2.md
> +You'll notice at the end of the template, there is a parameters section with only parameter: `BUILD_NAMESPACE`. We'll want to create a parameter file to set this value.
`s/only parameter/only one parameter/`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step2.md
> +Awesome, we're almost ready to run this! First we need to create the OpenShift project/namespace where the application will run.
`s/First/Before we do,/`

2018-08-27 23:04 UTC, etsauer commented on openshift-applier/step3.md
> +Now we are ready to run!
replace with: `Our project is all set, but we still need to install Applier in order to run it.`

2018-08-28 15:49 UTC, logandonley commented
Updated per @oybed & @etsauer 's suggestions. Thanks for the improvements.

2018-08-30 18:38 UTC, etsauer approved these changes
LGTM

2018-08-30 18:45 UTC, etsauer commented
@oybed since you're out for a few and @logandonley has addressed your comments, I'm going to dismiss your review so we can merge.

2018-08-30 18:45 UTC, merged